### ISSUE TITLE
Unicode Decode Error when parsing Stack-Overflow Queries

### ISSUE THREAD

**Issue by KiraThiessat** [rbergm/PostBOUND#1]
Using the database and queries from https://rmarcus.info/stack.html produces an error:

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 541: character maps to <undefined>`

<details>

![PostBound_Stack_Error](https://user-images.githubusercontent.com/22939771/196505987-294e5e1a-c697-4271-bae5-573ea9d87378.jpg)

With readlines-output:
![PostBound_Stack_Error_2](https://user-images.githubusercontent.com/22939771/196505269-1317bc42-05a0-4182-a54a-a2d7e4ab5bee.jpg)

</details>

**Comment by KiraThiessat** [comment]
Adding the option `encoding='utf-8'` to the open function solved the issue for me.

Edit: Typo

**Comment by rbergm** [comment]
This seems interesting, on which platform did you try to run the UES optimization?

**Comment by KiraThiessat** [comment]
I am using win10. Seems like its default encoding scheme is cp1252, which caused this error. I found this stack overflow entry about the topic:

[CP1252 Encoding](https://stackoverflow.com/questions/42070668/python-3-default-encoding-cp1252)

Seems like the save way is to explicitly state the encoding scheme when interacting with the file system.

**Comment by rbergm** [comment]
Alright, yeah this is a platform issue. Currently I am focusing on bringing PostBOUND to UNIX-based systems and also limit my testing to such platforms. The technical dimension of this issue is as follows: when using the `open` function to prepare for reading/writing files, Python uses a platform-specific default enconding when the parameter is not set explicitly. On UNIX systems this default is UTF-8, while Python uses CP1252 on win64. Since the workload files are also encoded in UTF-8 this works fine. However, we actually have no guarantee that this is always the case. Going forward, I see two general ways of fixing this issue:

1. enforcing all files to be encoded in UTF-8, thereby potentially forcing the user to convert files manually
2. introducing another parameter such as `--file-encoding` to customize this behaviour

At this point in time, I am unsure what the best way to solving this issue is, but the issue will definitely be resolved.

**Comment by rbergm** [comment]
Closing since this won't be an issue in the revamped PostBOUND implementation
